### DISCUSSION TITLE
GitHub Actionsとhuskyについて調査

### DISCUSSION THREAD

**Discussion by kagomen** [first-contributions-ja/first-contributions-ja.github.io#129] [90: 知識・知見の共有]
## 関連するイシュー
#124

**Comment by kazzyfrog** [comment]
コードの品質を担保するための取り組みとして、以下のようなことがあります！：
- prettier（フォーマッター）：決められたルールに沿って、コードを整形してくれる
- ESLint（リンター）：単純な構文エラーや、プロジェクト固有のコーディング規約に沿っているかチェックしてくれる

他にも、テストとか、カバレッジ（コード全体の何％がテストされているかを測る）とかがある。

**Reply by kazzyfrog** [reply]
上記を導入したら、
継続的にそれらを実行することを自動化・仕組み化してしまえば、手動で実行する手間がなくなって、楽です！
忘れる心配もないので、安全！

**Reply by kazzyfrog** [reply]
それらをどのタイミングで、自動で実行させるかですが、大きく２つに分けられそうです！
- GitHub上
- ローカルのコミットやプッシュ前のタイミング

GitHub上なら、GitHub Actionsで自動化できます！
両方使い分けることも、できます！
参考：[[Next.js]huskyとGitHubActionsで綺麗に開発し続けられる環境を整える](https://zenn.dev/ampersand/articles/e45c9a2c0af831#tailwind)

**Reply by kazzyfrog** [reply]
ローカルのコミットやプッシュ前のタイミングで実行する場合：

これは、ネイティブのGitにもともと[Git hooks（公式）](https://git-scm.com/book/ja/v2/Git-のカスタマイズ-Git-フック)というのがある！
リファレンスの`pre-commit`フックの説明：
> pre-commit フックは、コミットメッセージが入力される前に実行されます。 これは、いまからコミットされるスナップショットを検査したり、何かし忘れた事がないか確認したり、テストが実行できるか確認したり、何かしらコードを検査する目的で使用されます。 このフックがゼロでない値を返すと、コミットが中断されます。

つまり、Gitの機能として以下があります！
- コミットするタイミングで、決められたコマンド（テストやフォーマッター、リンターなど）を実行させる。
- それで、エラーが出たりしたらコミット失敗にする！

これは、ライブラリなしで、カスタマイズして使うことができる
参考：[【Git hooks】pre-commitフック導入](https://zenn.dev/sun_asterisk/articles/97d2b4be675c06)

**Reply by kazzyfrog** [reply]
ただ、このネイティブのGit hooksのカスタマイズ・管理・実行をより簡単に行うための、
ライブラリが結構たくさんあります！

フロント開発では、[husky + lint-staged](https://zenn.dev/g_okawara/articles/850d8e6729edfb)が１番人気！
参考：[git-hooks vs husky vs lefthook vs lint-staged vs pre-commit vs simple-git-hooks](https://npmtrends.com/git-hooks-vs-husky-vs-lefthook-vs-lint-staged-vs-pre-commit-vs-simple-git-hooks)

**Comment by kazzyfrog** [comment]
ちなみに今は、GitHub上で、mainブランチにコミットされたら、
next buildとPagesへのデプロイが行われるように、GitHub Actionsでプロセスを自動化しています！

**Comment by kagomen** [comment]
## 大雑把にCI/CDとは？
ビルド、テスト、デプロイを自動化すること。
Circle CIやJenkinsなどが代表的なCI/CDツール
<img width="607" alt="スクリーンショット 2024-03-29 18 37 41" src="https://github.com/first-contributions-ja/first-contributions-ja.github.io/assets/154225199/5ef40476-f9ce-4ab4-9bfd-ee9857046b51">

**Reply by kagomen** [reply]
## 大雑把なGitHub Actionsの使い方
.github/workflowにyamlファイルを置いて、設定を記述する
yamlファイルは複数作成可能

```yml
name: Deploy Next.js site to Pages // タイトル

on: // ここに発動条件を記述
  push:
    branches: ["main"]  // mainブランチにpushしたら発動させる

  workflow_dispatch:  // 手動実行で発動させる（オプション設定が必要なければ記述はこれだけでOK）

jobs:  // ここに発動内容を記述
  build: // 発動内容のタイトル
    runs-on: ubuntu-latest  // ランナーの指定
    steps: 
      - name: Checkout // アクションのタイトル
        uses: actions/checkout@v4  // GitHub Marketplaceから任意の発動内容（アクション）を探してきて記述
      - name: Detect package manager  // このように複数記述可能
        id: detect-package-manager
```

## 補足

- 希望のアクションが見つからない場合、自分でカスタムアクションを実装する必要がある
- `jobs`はデフォルトで並列実行される。上から順番に実行させたい場合は`needs`を記述する


## 参考
[GitHub Actions を使いこなせ！ -YouTube](https://youtu.be/sx-aIgP2S00?si=AjdxXjAl3hgNBjjy)
[GitHub Marketplace](https://github.com/marketplace?type=)
