### DISCUSSION TITLE
Labelの初期化と設定

### DISCUSSION THREAD

**Discussion by pss-aileen** [first-contributions-ja/first-contributions-ja.github.io#23] [【運営】相談・報告]
- 目的
  - 後でissueを探しやすくするため
  - 自分が取り組みやすいissueを探すため
- DiscussionsとIssuesとで共通で使える
- 個人的Labelの候補
  - issueで使うもの
    - docs: ドキュメント周り
    - feature: 新機能追加
    - fix: バグなどの修正
  - Discussionsで使うもの
    - ちょっと考え中
- ラベルの言語
  - 英語or日本語
- helpが欲しい時は直接メンションで

**Comment by pss-aileen** [comment]
参考

- [良い感じのGitHub issueラベル #GitHub - Qiita](https://qiita.com/shun_tak/items/d363b7c5d9e8fa19dc6b)
- [GitHub の Issue 運用が助かるラベル 26 個 #Zaim｜watura](https://wtr.io/n/nca91e5bfb920)
- [昔作ったGitHubのLabelを供養する](https://zenn.dev/sh090/articles/8291abdb1be48f5765ec)
- [GitHubのissueのフロントエンド向けラベルを精査したので、OctokitでLabel登録を自動化した #JavaScript - Qiita](https://qiita.com/heeroo_ymsw/items/cf9ae43b67b1a6548223)


ラベルも種類が多すぎると鬱陶しいのとルールの統一が出来なさそうなのでほどほどが良いかも...

**Comment by pss-aileen** [comment]
あった方が良いかなぁ〜
- `Priority: High`
- `Priority: Low`
- 進行中とか？

↑ただ、こういった優先度は、Projectsで管理すれば良いと思う
でも、一目でわかるのはラベルかなぁ..
GitHubActionsでProjectの何にあるかでラベルを自動でつける方法ないんかな

**Reply by pss-aileen** [reply]
あるらしい

以下GPT

はい、GitHub Actionsを使用して、プロジェクトのステータスに応じてラベルを追加または削除することができます。これを行うには、カスタムGitHub Actionsワークフローを作成し、プロジェクトのステータスが変更されたときにトリガーされるように設定します。以下に、基本的な例を示します。

<details>
<summary>詳細</summary>

1. **ワークフローファイルの作成**: `.github/workflows` ディレクトリにワークフローファイルを作成します。例えば、`project-labels.yml` という名前でファイルを作成します。

2. **ワークフローの定義**:
   ```yaml
   name: Project Labels

   on:
     project_card:
       types: [moved]

   jobs:
     update-labels:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Add or remove labels
           uses: actions/github-script@v3
           with:
             github-token: ${{secrets.GITHUB_TOKEN}}
             script: |
               const projectId = 1; // ここにプロジェクトのIDを設定します
               const columnIdToLabelMapping = {
                 '123456': 'In Progress', // ここにカラムIDとラベルのマッピングを設定します
                 '789012': 'Done',
               };
               const columnId = context.payload.project_card.column_id;
               const issueNumber = context.payload.project_card.content_url.split('/').pop();
               const label = columnIdToLabelMapping[columnId];
               if (label) {
                 // すべてのラベルを削除してから、適切なラベルを追加します
                 await github.issues.removeAllLabels({
                   owner: context.repo.owner,
                   repo: context.repo.repo,
                   issue_number: issueNumber,
                 });
                 await github.issues.addLabels({
                   owner: context.repo.owner,
                   repo: context.repo.repo,
                   issue_number: issueNumber,
                   labels: [label],
                 });
               }
   ```

この例では、プロジェクトカードが移動されるたびにワークフローがトリガーされ、カードが配置されたカラムに応じてラベルを更新します。`projectId` と `columnIdToLabelMapping` の値は、あなたのプロジェクトとカラムに合わせて適切に設定する必要があります。また、このスクリプトは、カードがイシューにリンクされていることを前提としています。

GitHub ActionsのドキュメントやGitHub APIのドキュメントを参照することで、さらに複雑なロジックを実装することも可能です。
</details>
