### DISCUSSION TITLE
フォーマットのためのGitHubActions

### DISCUSSION THREAD

**Discussion by pss-aileen** [first-contributions-ja/first-contributions-ja.github.io#261] [90: 知識・知見の共有]
色々調査、情報整理のために書いていきます

### related
- https://github.com/first-contributions-ja/first-contributions-ja.github.io/discussions/248#discussioncomment-10021999
- https://github.com/first-contributions-ja/first-contributions-ja.github.io/pull/250
- #262 

### 関係あるかわからないが気になった記事
- [GitHub Actions 動作時に husky install を実行しないようにする #npm - Qiita](https://qiita.com/tommy_aka_jps/items/f90502d4845d34c195da)

**Comment by pss-aileen** [comment]
## そもそも現状どうなっているか
- huskyがcommit時にフォーマットするようになっている
- 具体的に何がどうやってフォーマットしているか
- list-stagedが変更されたファイルに対してのみlintやformatをする

package.json
```json
  "lint-staged": {
    "*.{vue, ts, js}": "eslint --fix",
    "*.{js,jsx,ts,tsx,vue,css,html,md,json,cjs}": "prettier --write"
  }
```

#### 参考
- https://github.com/first-contributions-ja/first-contributions-ja.github.io/pull/183
- https://zenn.dev/risu729/articles/latest-husky-lint-staged
- https://github.com/first-contributions-ja/first-contributions-ja.github.io/discussions/129

**Comment by pss-aileen** [comment]
## GitHubActionsをしたあとに、再びコミットしようとしたら発生したエラー

https://github.com/pss-aileen/first-contributions-ja.github.io/pull/1

```sh
# list-stagedを準備スタート
[STARTED] Preparing lint-staged...
# list-staged 準備できた
[COMPLETED] Preparing lint-staged...
# ステージされたファイルに対してタスクを実行 -> tasks がなんなのか？ -> たぶん package.jsonに書かれたこと？ -> 調査
[STARTED] Running tasks for staged files...
[STARTED] package.json — 1 file
[STARTED] *.{vue, ts, js} — 0 files
[STARTED] *.{js,jsx,ts,tsx,vue,css,html,md,json,cjs} — 1 file
[SKIPPED] *.{vue, ts, js} — no files
# Prettier のフォーマット開始
[STARTED] prettier --write
# Prettier のフォーマット終了
[COMPLETED] prettier --write
[COMPLETED] *.{js,jsx,ts,tsx,vue,css,html,md,json,cjs} — 1 file
[COMPLETED] package.json — 1 file
[COMPLETED] Running tasks for staged files...
# タスクからの修正を適応
[STARTED] Applying modifications from tasks...
# 失敗: 
[FAILED] Prevented an empty git commit!
[STARTED] Reverting to original state because of errors...
[COMPLETED] Reverting to original state because of errors...
[STARTED] Cleaning up temporary files...
[COMPLETED] Cleaning up temporary files...

  ⚠ lint-staged prevented an empty git commit.
  Use the --allow-empty option to continue, or check your task configuration

husky - pre-commit script failed (code 1)
```

**Reply by pss-aileen** [reply]
huskyの厳密な動きを知りたい

**Reply by pss-aileen** [reply]
GPTより
https://git-scm.com/book/en/v2/Getting-Started-What-is-Git%3F

> 1. **ファイルの状態**:
>    - **Modified（修正済み）**: ファイルを変更したが、その変更をまだコミットしていない状態です。つまり、ファイルは変更されていますが、Gitの管理下にはまだ置かれていません。
>    - **Staged（ステージ済み）**: 変更されたファイルを次のコミットに含める準備が整った状態です。この状態でファイルは「ステージ」され、次回のコミットに含まれることになります。
>    - **Committed（コミット済み）**: 変更がローカルのGitデータベース（リポジトリ）に安全に保存されている状態です。
> 
> 2. **Gitプロジェクトの主要なセクション**:
>    - **Working Tree（作業ツリー）**: 現在作業しているディレクトリで、実際のファイルが存在する場所です。ここでファイルの編集や修正が行われます。
>    - **Staging Area（ステージングエリア）**: 次のコミットに含めたい変更を一時的に置いておく場所です。`git add`コマンドでファイルをここに追加します。
>    - **Git Directory（Gitディレクトリ）**: Gitが管理するデータベースの場所で、コミットされた変更が保存されています。リポジトリの中にあり、`.git`フォルダがこれに該当します。
> 
> この三つの状態とセクションの理解は、Gitを使ったバージョン管理の基本的な流れを把握するために重要です。

**Comment by pss-aileen** [comment]
## GitHubActionsでのエラー

https://github.com/pss-aileen/first-contributions-ja.github.io/actions/runs/10005217373/job/27655469728#step:7:19

```
Run git diff --exit-code
  git diff --exit-code
  shell: /usr/bin/bash -e {0}
diff --git a/.vscode/extensions.json b/.vscode/extensions.json
index 97d8a46..1d7ac85 100644
--- a/.vscode/extensions.json
+++ b/.vscode/extensions.json
@@ -1,6 +1,[3](https://github.com/pss-aileen/first-contributions-ja.github.io/actions/runs/10005217373/job/27655469728#step:7:3) @@
 {
-    "recommendations": [
-      "dbaeumer.vscode-eslint",
-      "esbenp.prettier-vscode"
-    ]
-  }
\ No newline at end of file
+  "recommendations": ["dbaeumer.vscode-eslint", "esbenp.prettier-vscode"]
+}
Error: Process completed with exit code 1.
```

**Comment by pss-aileen** [comment]
### format.yml

```yml
name: Format Code

on:
  # プルリクエストが開かれた時に実行する
  pull_request:
    types:
      - opened
  # 手動でも実行できるようにする
  workflow_dispatch:

# 作業内容
jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Node.js をセット
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # npm install で依存関係をインストール
      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npm run format

      - name: Run Linter
        run: npm run lint

      - name: Check for formatting changes
        run: git diff --exit-code
        continue-on-error: true
```

**Comment by pss-aileen** [comment]
## 現状
- 自分の環境でhuskyが実行された
- プルリクを開くと、GitHubActionsが実行された
- ただ、これは vscode extensions.json が変更されただけで、別に Contributions.json は変更されていない
- 自分たちはhuskyが走っているのでフォーマットされている...
- huskyが通っていても、問題ないようにしたい... <- これだ！
- 結局フォーマットされてコミットファイルが変更されてないよっていうのは、リモート？（コミット済み）はすでに前のコミットでhuskyされたものが上がっていて、またインデントを減らしてコミットしようとしたらhuskyが動いたけど、それはリモートのコードと違いがないので、コミットできなかった...ってことかな...

**Reply by pss-aileen** [reply]
- であれば、何か変更を加えればよし？
- Contributions.jsonにインデント以外の変更を加えたところいけた
- たた、問題はnpm install してない場合なので、node_modulesを消す
- またコミットできなかった
- 原因はhuskyが走っていること
- node_modulesがあるからhuskyが走るのでは？
- とりあえず .husky を消してコミット -> できた -> ちゃんと検証するためにはcloneを1からやって試した方がいい

**Reply by pss-aileen** [reply]
- プルリク開いて、そのあとにコミットすると format されない
- 試しに手動でフォーマットしてみた https://github.com/pss-aileen/first-contributions-ja.github.io/actions/runs/10006074740
- 成功してるっぽいが、プルリクをみても反映されている様子なし

**Reply by pss-aileen** [reply]
あとで状況整理

**Reply by pss-aileen** [reply]
追加でプッシュすると結局整形されてないものがあがってくるので、最終的にmainにpushした時に走らせた方がいいかな？

**Reply by kazzyfrog** [reply]
確かに、PRのタイミングだと、
その後のpushでは作動しなくなりますね！
そのケースを見落としてました。。！

欲を言えば、レビュー時に、フォーマットが効いていると嬉しいので、
pushとPRの[複数](https://docs.github.com/ja/actions/using-workflows/triggering-a-workflow#using-multiple-events)トリガー設定して、両方で走らせてもいいかもですね！

**Reply by pss-aileen** [reply]
@kazzyfrog

いろいろヒントになるような記事などありがとうございます🙇


色々自分のリポジトリで試した結果、プルリクエストが作られた段階でフォーマットが走るような GitHub Actions を作成することはできました。

以下、流れです。

＜フォーマットされてそのままマージする場合＞

1. プルリクエスト作成 
2. フォーマットされる 
3. もし修正があれば新しくコミットが作成される（リモート）
5. レビュー、マージ

＜フォーマットされてさらに修正を加える場合＞

1. プルリクエスト作成 
2. フォーマットされる 
3. もし修正があれば新しくコミットが作成される（リモート）
5. さらに修正したい場合は新しいコミットをローカルでpullして作業
6. プッシュ
7. レビュー、マージ

その上で、以下が気になります。

- プルリク作成時にGitHubActionsを走らせてコードがフォーマットされ、さらにコミットを積みたい場合、ユーザーさんがpullする方法でつまづかないか
- プルリク作成に加え、プッシュ時にフォーマットがされコードに変更が生じた場合、それをpullして、修正する手間が発生する

以上を考えると
GitHubActionsをプルリク作成時に走らせるのではなく、
たまに私たち誰かがフォーマットするか（issueたててフォーマット）、
GitHubActionsを使って手動でフォーマットするか...のほうが、ユーザーさんの引っ掛かりポイントは少ないのかなと思いました。

どう思いますか...？

**Reply by kazzyfrog** [reply]
> プルリク作成時にGitHubActionsを走らせてコードがフォーマットされ、さらにコミットを積みたい場合、ユーザーさんがpullする方法でつまづかないか

これは確かにそうですね！
少し手間が増えそうだと思いました！！

> プルリク作成に加え、プッシュ時にフォーマットがされコードに変更が生じた場合、それをpullして、修正する手間が発生する

プロジェクトのmainブランチに対してのpush（現在走っているデプロイのワークフロー）のタイミングでの実行なら、
マージした後に、最後に一回フォーマットが走る感じで良さそうかな、、？と思いました！

あれ、もしかしたら自分が何か勘違いしているかもなので、
気になることがあればぜひ聞いてください！🙌

**Reply by kazzyfrog** [reply]
以下のような感じでできたら良さそう。。なのかも？と思っている感じです！

1. プルリクエスト作成
2. レビューに対応（必要に応じて修正）
3. 承認
4. mainブランチにマージ
5. フォーマットが走る！

**Reply by pss-aileen** [reply]
ご確認ありがとうございます！

個人的には特に相違はないかな...？と思っていましたが、どうでしょう😳！？あら？😱私こそなにか勘違いしてるかもしれません！

> プロジェクトのmainブランチに対してのpush（現在走っているデプロイのワークフロー）のタイミングでの実行なら、
> マージした後に、最後に一回フォーマットが走る感じで良さそうかな、、？と思いました！

こちらですが、ご意見を確認した上でまとめると

デプロイ時、以下のGitHub Actionsの流れの中で Node.js のセットアップが終わった後に Prettier と Linter 走らせてビルドするのが良いかなと思いました。

https://github.com/first-contributions-ja/first-contributions-ja.github.io/blob/main/.github/workflows/nextjs.yml#L74-L75

↑このコードのあとにフォーマットを走らせるイメージ

<details>
<summary>自分の思っている最終形態 YML（コード折りたたんでます）</summary>

これで正しく動くかは検証が必要ですが、以下を想定しています。

```yml
# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy Next.js site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            echo "runner=yarn" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "${{ github.workspace }}/package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Unable to determine package manager"
            exit 1
          fi
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ steps.detect-package-manager.outputs.manager }}
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          # Automatically inject basePath in your Next.js configuration file and disable
          # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
          #
          # You may remove this line if you want to manage the configuration yourself.
          static_site_generator: next
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
      - name: Install dependencies
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
      # 🟥 フォーマット スタート 🟥
      - name: Run Prettier
        run: npm run format
      - name: Run Linter
        run: npm run lint
      # 🟥 フォーマット 終わり 🟥
      - name: Build with Next.js
        run: ${{ steps.detect-package-manager.outputs.runner }} next build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```

</details>


もし、デプロイ後にフォーマット用のGitHubActionsがmainブランチで走ってコードの変更があった場合、またビルドしなくちゃいけなくなると思うので...！

**Reply by pss-aileen** [reply]
> 以下のような感じでできたら良さそう。。なのかも？と思っている感じです！

あ、こちらの投稿今気がつきました！

そんな感じですかね！

**Reply by kazzyfrog** [reply]
> デプロイ時、以下のGitHub Actionsの流れの中で Node.js のセットアップが終わった後に Prettier と Linter 走らせてビルドするのが良いかなと思いました。

確かにそうですね！
ファイルまとめて良さそうです！

認識も同じでした！！w
フォーマット終わりに、git-auto-commit-actionでコミット積んで、ビルドすればうまくいきそう？ですね👍

**Comment by kazzyfrog** [comment]
「git diff –exit-code」が不要なのかもです！
> git diff --exit-codeはステージ前（git add前）のファイル差分を確認し、差分がなければ次の処理へと移り、差分があれば処理を強制終了するコマンドです。
[参考](https://prograshi.com/general/git/what-is-exit-code-in-git-diff/)

これだけでは、フォーマットに対してコミットが積まれていない感じかもです

**Reply by kazzyfrog** [reply]
その上で、[git-auto-commit-action](https://github.com/stefanzweifel/git-auto-commit-action)という、アクションをワークフロー内で使えるので、これが便利かもです！

下記などでも、
どれも同じような方法で作成されていたので、参考までに貼っておきます！
- [ESLint, Prettierをチーム開発で運用する〜VSCode, Github Actions編〜](https://blog.uzumaki-inc.jp/eslint-prettiervscode-github-actions)
- [GitHub にコード整形してもらおう - GitHub Actions でコード整形&コミット](https://qiita.com/Ouvill/items/7b6df0e9b981093b330f)
- [【共同開発】GitHub Actions × PrettierでPush時にコードを整形する](https://tech.playground.style/workstyle/github-actions-prettier/)

**Reply by pss-aileen** [reply]
- [ESLint, Prettierをチーム開発で運用する〜VSCode, Github Actions編〜](https://blog.uzumaki-inc.jp/eslint-prettiervscode-github-actions)
  - ESLintをGitHubActionsで実行するとGitHubActionsがプルリクにコメントしてくれる
  - 権限 -> 実行時にコメントを書き込んだりすることができる？ -> 権限またあとで
- [GitHub にコード整形してもらおう - GitHub Actions でコード整形&コミット #JavaScript - Qiita](https://qiita.com/Ouvill/items/7b6df0e9b981093b330f)
  - git-auto-commit-action: GitHubでコードの内容を変更したとき、内容をコミットするもの
  - 整形後のpush注意
- [【共同開発】GitHub Actions × PrettierでPush時にコードを整形する｜Playground発！アプリ開発会社の技術ブログ](https://tech.playground.style/workstyle/github-actions-prettier/)
  - シンプルな実行
- [stefanzweifel/git-auto-commit-action](https://github.com/stefanzweifel/git-auto-commit-action)
  - ワークフローで変更されたファイルをコミット、GitHubリポジトリにプッシュバックする
  - コミットはGitHub Actionsの名前
  - 最後のコミットを行ったユーザーによって共同作成される

**Comment by pss-aileen** [comment]
とりあえず変更してみて
https://github.com/pss-aileen/first-contributions-ja.github.io/actions/runs/10043049735
これでformatできた。

以下、疑問点、知りたいこと。

- format して、build、deployの順にできるのか？すでにそうなっているのか？ -> `needs` でできる
- permission の書き方が正しいのか不明 -> わかってないので調べる -> それぞれのjobに権限を与える
- なぜ build と deploy がつながっているのか -> `needs`

**Reply by pss-aileen** [reply]
GPTメモ

- permission、わけれるっぽい

```yaml
name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Format job
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npm run format

      - name: Run Linter
        run: npm run lint

      - name: Check for formatting changes
        run: git diff --exit-code
        continue-on-error: true

      - name: Auto commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[GitHubActions] Format"

  # Build job
  build:
    runs-on: ubuntu-latest
    needs: format

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-

      - name: Install dependencies
        run: npm ci

      - name: Build with Next.js
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .next

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```
